services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    restart: always
    ports:
      - 8080:8080
      - 9000:9000
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\nhost: http://localhost/auth\nConnection: close\n\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 60s
    command:
      start-dev
      --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://192.168.0.201/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_PROXY_HEADERS: xforwarded

      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KEYCLOAK_IMPORT: /opt/keycloak/data/imports/default-realms.json
    volumes:
      - ./realms/default-realms.json:/opt/keycloak/data/import/default-realms.json
