services:
  sonatype-nexus3:
    image: sonatype/nexus3:latest
    restart: always
    #network_mode: host
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:8081/service/rest/v1/status/writable"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 60s
    volumes:
      - ./data:/nexus-data