services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 60s
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password      
    volumes:
      - ./data:/var/lib/postgresql/data
      
secrets:
   db_password:
     file: ./POSTGRES_PASSWORD