services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 60s
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  my-home: